name    'saz-motd'
version '2.2.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage "Message Of The Day" via Puppet'
project_page 'https://github.com/saz/puppet-motd'
